### ISSUE TITLE
Website Flow Suggestion - Partnerships

### ISSUE THREAD

**Issue by koronkowy** [SeaGL/organization#161]
Hiya! I think that it would be easier to navigate if when you clicked on Sponsors that you had some of the verbiage there instead of nested under the year 2021 itself. Maybe flip how that site flow works? Click sponsors > straight to 2021 > another nested dropdown to view other years and/or a mention of it on the bottom of 2021.

Right now people have to dig kind of deep to get to the prospectus and other info.

See: https://seagl.org/sponsors/
and: https://seagl.org/sponsors/2021.html

**Comment by altsalt** [comment]
@AndrewKvalheim wanted to make sure you had :eyes: on this

**Comment by AndrewKvalheim** [comment]
Good idea, thanks. I’ve [changed](https://github.com/SeaGL/seagl.github.io/commit/25bb199ddc94db82ea8f0a486c325c0ace778308) the main menu to link directly to the latest year, and added some navigation between years at the bottom since that was simple to implement. Happy to hear suggestions of further refinements.

**Comment by koronkowy** [comment]
This looks great and should be good to close! The bottom is fantastic.
