### ISSUE TITLE
Budget: graphical recordings

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#177]
From previous meeting notes (programming): $750 (4 keynotes) / $5,600 (36 talks) for graphical recordings

**Comment by koronkowy** [comment]
Also relevant: https://github.com/SeaGL/organization/issues/138

**Comment by lufthans** [comment]
Finance committee approved using SeaGL funds as a backstop for the keynotes if not specifically sponsored.

Graphical recordings for each of the talks will require sponsorship, a sponsor option and description will be added to the sponsorship prospectus.

In light of using this as a speaker gift, we will also ask if it's less expensive to make graphical recording after the talk from recordings rather than live.
