### ISSUE TITLE
Linux Magazine print ads

### ISSUE THREAD

**Issue by funnelfiasco** [SeaGL/organization#61]
I can offer up to 3 full-page ads in our print and digital magazines. You can run these all in Linux Magazine/Linux Pro Magazine and we also could run an ad in our bi-montly ADMIN Network & Security magazine. Here are the deadlines for the issues that will happen prior to the start of your event:
ADMIN #64 -- USA on-sale date 7/2/21; materials due May 7
Linux Magazine #248 (July 2021) -- USA on-sale date 7/2/21; materials due May 14
Linux Magazine #249 (August) -- USA on-sale date 7/30/21; materials due June 11
ADMIN #65 -- USA on-sale date 9/3/21; materials due July 9
Linux Magazine #250 (Sept) -- USA on-sale date 9/3/21; materials due July 16
Linux Magazine #251 (Oct) -- USA on-sale date 10/1/21; materials due August 13

The specs for the full-page ad are as follows:
Type area: 184 x 266
Trim size: 210 x 297

Trim: The final dimensions assuming perfect placement.
Bleed: Continue colors and graphical backgrounds 3mm beyond trim at any page edge.
Live Area: Space within the ad for locating text and important graphic elements. Allow 5mm from the edge of the Live Area to the trim line.

File format: Send closed (non-editable) files as high-resolution PDF
Graphics: Artwork should use the CMYK color space.
Resolution: 300 dpi minimum.
Crop marks: Include crop marks outside the bleed size to indicate how your ad should be positioned and cropped.
Fonts: All fonts must be embedded.

**Comment by funnelfiasco** [comment]
Looking at the deadlines, we may want to prioritize this over the newsletters. They're giving us up to three slots, and we have only three more slots available. If we only get 2, that's okay, of course, but if we can get the max they're willing to oiffer, we might as well. :-)

**Comment by mateuskrause** [comment]
I took a look at the deadlines and we can not share about CfP (call ends august, the next one we can send will have on-sale date in september).
In this case, we have to focus on the call for volunteers, I think. As we have full page, we can tell about SeaGL, things like Career Expo and some keynotes (?).

@funnelfiasco, can you confirm some things that we can add?

About the text, I thought about getting some inspiration from the blog posts.

**Comment by funnelfiasco** [comment]
>In this case, we have to focus on the call for volunteers, I think. As we have full page, we can tell about SeaGL, things like Career Expo and some keynotes (?).

I don't think we'll have the keynotes set in time to meet the deadlines. We could mention the career expo, tea exchange ("TeaGL"), and that we're looking for volunteers. 

Even though we have a full page, I don't think we'll want to put too much text on there

**Comment by mateuskrause** [comment]
I created a draft for the text:

_SeaGL 2021 - Join Us!_
_Seattle GNU/Linux Conference returns for the ninth year!_

_We’re a community-focused Free/Libre Open Source Software annual event in Seattle, and since last year, all over the world virtually! Join us for many talks and keynotes, with no registration required!_

_This year we will host the 2nd Career Expo, a place where you can send your resume for reviews and career guidance, via private consultation. And of course, 4th TeaGL, with virtual tea time and online tea swap!_ 

_Interested in helping make SeaGL happen? Lend a wing to our all volunteer eﬀort! Want to sponsor? Contributions will have a real and lasting effect in the FLOSS community!_

_November 5th & 6th, 2021_
_Virtual Conference_

What could be improved in the text? Maybe is too big and I'm not sure about the Career Expo and TeaGL paragraph. What do you think?

**Comment by funnelfiasco** [comment]
Looks good. A few small suggestions:

* Change "Join us for many talks and keynotes, with no registration required!" to "Join for free us, with no registration required!"
* Change "4th TeaGL, with virtual tea time and online tea swap!" to "TeaGL—our virtual tea time and online tea swap!"

I also don't see the URL. We should include seagl.org on the page, in addition to having the QR code.

**Comment by altsalt** [comment]
Here's a couple of changes, incorporating @funnelfiasco 's as well:

> SeaGL 2021 - Join Us!
> Seattle GNU/Linux Conference returns for the ninth year!
> 
> We’re an annual community-focused free/libre/open source software, hardware, and culture event in Seattle, and since last year, _virtually_ all over the world! Join us for free, no registration required!
> 
> This year, alongside the keynotes and many presentations, will see the return of the **Career Expo**—providing resume reviews and career guidance, **TeaGL**—our virtual tea time and online tea swap, and many more socialization opportunities!
> 
> Interested in helping make SeaGL happen? Lend a wing to our _all volunteer eﬀort_! Connected to a company who wants to sponsor? Contributions will have a _real and lasting impact_ on the FLOSS community!
> 
> November 5th & 6th, 2021
> Virtual Conference

**Comment by mateuskrause** [comment]
Full ad draft [here](https://drive.google.com/file/d/1j8yPrVJt_Hy-QQYdAjwDbLNq5YVvXQqe/view?usp=sharing).

The text contains all the changes and have the "visit seagl.org for more info" phrase. What do you think about the font sizes? Because of the deadline, I reused the _style_ from website ads (sort of). Do you have any suggestions?

**Comment by funnelfiasco** [comment]
It's a little more text-full than I'd like, but I'm not sure we can do much
about that without significant edits.

I will say that I like the text size.

Maybe we can bold a few phrases, or put them in a different color to
highlight. But that might be too distracting...

**Comment by mateuskrause** [comment]
We can discuss more for the next ones. For now, Andrew helped me and I think we have the final doc for the first ad (I also have send this final version for him to take a look). Useful link: Linux Magazine [ad guidelines](https://www.linux-magazine.com/content/download/20992/179622/file/Linux_Magazine_Ad_Guidelines.pdf).

Changes: I updated the QR code to a vector version, instead of png (to fit the DPI requirement); Increased the background size to the bleeding area (as the ad have backgrounds that should go to the edge of the page); Included crop marks outside bleed size.

I think everything is right: CMYK colors, 300 DPI, Bleed, Crop Marks. Since all text is as vectors, no fonts to embed.

The file is on Google Drive at `Outreach/2021/ads/print_ads/9jul_ADMIN_65/seagl2021_print_ad_9jul.pdf` and can be viewed [here](https://drive.google.com/file/d/1O1SlSuxj31-q_IcgaT1nsmL9ykR2n0a6/view?usp=sharing).

**Comment by mateuskrause** [comment]
**Update:** Andrew gave his feedback and apparently we confused bleed marks with crop marks; Also, just to be sure, I increased the DPI to 600.

I uploaded the file with the changes. In fact, is the same file, but version 2.

**Comment by funnelfiasco** [comment]
Okay, great. I'll get this sent to Linux Mag now

**Comment by altsalt** [comment]
Can we close this issue?

**Comment by funnelfiasco** [comment]
Do we want to make any changes for the last print run this fall, or use the existing design?

**Comment by mateuskrause** [comment]
@funnelfiasco I think we can change for the last print (LM 251), with other infos that we think is important more close to the conference date.

@altsalt what do you think about using task lists here? This first ad that will be on the LM 250 and ADMIN 64 is finished and was sent. Until the LM 251 deadline we can adapt the doc as I said above.

**Comment by altsalt** [comment]
Unsure what the task list is, but I trust ya that this is progressing just swimmingly :)

**Comment by funnelfiasco** [comment]
Since we won't have keynote speakers confirmed by the final deadline, let's just stick with what we have. Great work, @mateuskrause!

**Comment by funnelfiasco** [comment]
Keynote speakers to include on the sept 10 due date:

* Cory Doctorow
* Morgan Lemmer-Webber
* Chris Lemmer-Webber
* Marie Nordin
* Elana Hashman

**Comment by altsalt** [comment]
Might want to do `Christine & Morgan Lemmer-Webber`, also please note to s/Chris/Christine/ everywhere. Thanks!

**Comment by mateuskrause** [comment]
I thought about add the speaker info to the second paragraph of the current print ad text, something like:

> This year, our lineup of awesome keynote presenters will include: Cory Doctorow, Christine & Morgan Lemmer-Webber, Marie Nordin, Elana Hashman and more! Also, the return of the Career Expo, and our virtual tea time and online tea swap, TeaGL.

Or maybe changing the end to

> Alongside the socialization opportunities, the return of the Career Expo, and our tea time TeaGL.

Just to compare, the second paragraph of the first print ad:

> This year, alongside the keynotes and many presentations, will see the return of the Career Expo - providing resume reviews and career guidance, TeaGL - our virtual tea time and online tea swap, and many more socialization opportunities!

At the end, we're limited to about 254 characters for this section. What do you think?

**Comment by altsalt** [comment]
Going forward, let's use the keynote ordering of:
> Marie Nordin, Christine & Morgan Lemmer-Webber, Elana Hashman, and Cory Doctorow

How's this sound?
> This year will feature dozens of presentations including our keynotes: Marie Nordin, Christine & Morgan Lemmer-Webber, Elana Hashman, and Cory Doctorow! Also many community connections, the Career Expo, and our shipped tea swap with virtual TeaGL party!

**Comment by mateuskrause** [comment]
Sounds very good!
We can bold the names to highlight, like this:

![image](https://user-images.githubusercontent.com/47651648/132527121-42af0322-caba-4290-9205-7fb58879d67d.png)

Do we have any other thing to change/add?

**Comment by funnelfiasco** [comment]
I like it!

**Comment by altsalt** [comment]
LGTM!

**Comment by mateuskrause** [comment]
I exported the new file, the same way as before (CMYK, 600DPI, etc), [here](https://drive.google.com/file/d/13r0WMeOX2RWQBb1LaPzk0EOVPYYvWOR4/view?usp=sharing).

It may happen that "ll" looks in bold, but it's only happening in the google drive preview.

If the file is correct, I think we can send to LM.

**Comment by funnelfiasco** [comment]
LGTM. I don't see the bold "ll" when I download it and view locally.

**Comment by mateuskrause** [comment]
@funnelfiasco, can I send the file to LM?

**Comment by funnelfiasco** [comment]
Go for it!

**Comment by mateuskrause** [comment]
Unfortunately, LM 251 has already been printed :(
