### ISSUE TITLE
Reach out to James Mason, lead of LFNW and OSEM maintainer

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#68]

**Comment by koronkowy** [comment]
@altsalt and @AndrewKvalheim did this happen or will it be happening?

**Comment by altsalt** [comment]
The goal here is to have a list of code changes which Jame might review. I am okay to draft the email when that list exists. The longer term maintenance is not relevant to this issue, but should probably have an issue of its own, as a volunteer need.

**Comment by koronkowy** [comment]
If @altsalt @SeaGL/tech can come up with part 2 of that, a long term idea of need I'd be happy to help try and find something like that. Conferences are a good opportunity to passively bring requests like this but it does sound like this might be a post-conference long term goal type issue vs current need?

Also thank you kindly @AndrewKvalheim, that sounds like a position I wouldn't envy being in. I hope I can offer any support possible or wag a stick wherever so that we can get more support. My goal is that no one feels abandoned in any organizing area even when volunteer support wanes or changes due to life or work or otherwise.

**Comment by koronkowy** [comment]
I am going to close this because I think it's at a standstill. Probably going to make a future listing for OSEM moderator in the volunteer needs.
